### ISSUE TITLE
Simplify quality metric implementation

### ISSUE THREAD

**Issue by danjampro** [AstroHuntsman/huntsman-drp#93]
This is too complicated: 
```
quality:
  raw:
    science:
      get_wcs:
        has_wcs: true
    flat:
      quality:
        rawexp:
          flipped_asymmetry:
            flip_asymm_h:
              less_than: 100
            flip_asymm_v:
              less_than: 60
          clipped_stats:
            well_fullfrac:
              greater_than: 0.13
              less_than: 0.19
```
We should remove the "rawexp" subheading and get rid of function names (e.g. clipped_stats), just keeping metric names.
